### PR TITLE
Use qubes-infrastructure-mirrors as submodule

### PR DESCRIPTION
**Pull request by fepitre**
It eases solving issues with python version and external dependency.

### CODE REVIEW

**Comment by marmarek** [comment]
You need to update submodule to the new infrastructure-mirrors version

**Comment by marmarek** [comment]
black fails, likely due to different expected line length...

**Comment by marmarek** [comment]
And also publish test fails...

**Comment by fepitre** [comment]
> black fails, likely due to different expected line length...

yes this one should be solved into another PR just for linting I think?

**Comment by fepitre** [comment]
@marmarek I give up on retrying archlinux job...

**Review by marmarek — APPROVED** [review]

**Pull request merged**
