### PR TITLE
support v2 hybrid torrent

### PR DESCRIPTION
**Pull request by zpc0**
QubesOS/qubes-issues#8621

Is it OK to depend on Fedora-only package?

### CODE REVIEW

**Comment by marmarek** [comment]
> Is it OK to depend on Fedora-only package?

No, there needs to be a fallback to something on Debian/Ubuntu.

**Comment by zpc0** [comment]
Thank you for answering.
I added `mktorrent` as fallback.
If `make_torrent` is not available (on Debian etc), `mktorrent` is used.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
One more thing we need to handle is providing upload URL to tracker from what the conf tells, e.g. https://github.com/QubesOS/qubes-builderv2/blob/main/example-configs/builder-devel.yml#L242

**Comment by zpc0** [comment]
> One more thing we need to handle is providing upload URL to tracker from what the conf tells, e.g. https://github.com/QubesOS/qubes-builderv2/blob/main/example-configs/builder-devel.yml#L242. @zpc0 would you like to add it?

Sorry if I misunderstood your comment, the public BitTorrent tracker does the job by simply listing trackers in the torrent file.
So I think it is not necessary to upload something to the tracker.

**Review by marmarek — APPROVED** [review]

**Comment by fepitre** [comment]
> > One more thing we need to handle is providing upload URL to tracker from what the conf tells, e.g. https://github.com/QubesOS/qubes-builderv2/blob/main/example-configs/builder-devel.yml#L242. @zpc0 would you like to add it?
> 
> Sorry if I misunderstood your comment, the public BitTorrent tracker does the job by simply listing trackers in the torrent file. So I think it is not necessary to upload something to the tracker.

The URL about where is the ISO is not fixed, e.g., it's not always `https://ftp.qubes-os.org/iso/`. For weekly builds, it's `https://qubes.notset.fr/iso-testing/`.

**Comment by zpc0** [comment]
Thank you for the clarification.

To support more flexible configuration, I think rewriting this script to Python would be an option, but I have no resources to do so. Sorry.

**Pull request merged**
