### PR TITLE
Set option dispvm to qube setting default_dispvm

### PR DESCRIPTION
**Pull request by ben-grande**
Fixes: https://github.com/QubesOS/qubes-issues/issues/8842

### CODE REVIEW

**Comment by fepitre** [comment]
This is misleading, one might think we use dom0 to do actual stuff. I don't want to have it in the default configuration files.

**Comment by marmarek** [comment]
> This is misleading, one might think we use dom0 to do actual stuff. I don't want to have it in the default configuration files. We could use some special pattern but clearly not `dom0`. @marmarek what do you think?

Well, the current API is that directing call to dom0 will create DispVM based on default template (for that qube). But for the config file, maybe builder could translate "None" into dom0, so when no option is set, it would use the default property?

**Comment by marmarek** [comment]
It seems to be already the case if the option is not set. There is currently no way to unset the option (via cmdline, included config, etc), but one can set it to "dom0" (which indeed may be counter-intuitive). Maybe qubes executor should translate empty name (or "None") into "dom0"?

**Comment by ben-grande** [comment]
Another option would be for the API to support `@dispvm` argument for `admin.vm.CreateDisposable`. Tried with the builder but it returns an empty string.

**Comment by ben-grande** [comment]
> Maybe qubes executor should translate empty name (or "None") into "dom0"?

I still find this solution confusing, it seems like there won't be a dispvm used. If it were to translate something, it should be `@dispvm`, although that is reserved character that won't work when using the qrexec call from the command line, it is being used in the intended way. The downside is `@` is special and the string must be quoted. The upside is that the example configs already has it quoted, so people learning from there will use it correctly.

See alternative implementation:

- https://github.com/QubesOS/qubes-builderv2/pull/135

**Comment by ben-grande** [comment]
Closed as alternative was merged https://github.com/QubesOS/qubes-builderv2/pull/135

**Pull request closed without merging**
